"""add sale status

Revision ID: 13c5681e5059
Revises: f9ef7b92448b
Create Date: 2025-08-04 02:42:35.041002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c5681e5059'
down_revision = 'f9ef7b92448b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('fuel', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('trim', sa.String(length=50), nullable=True),
    sa.Column('year', sa.String(length=20), nullable=True),
    sa.Column('mileage', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('price', sa.String(length=50), nullable=True),
    sa.Column('manufacturer', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('sub_model', sa.String(length=50), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('thumbnail', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('판매중', '판매완료', name='salestatusenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale')
    # ### end Alembic commands ###
