"""Change status from enum to boolean

Revision ID: 5e322cfca427
Revises: 13c5681e5059
Create Date: 2025-08-04 02:46:31.916473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e322cfca427'
down_revision = '13c5681e5059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.Boolean(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False)

    # ### end Alembic commands ###
