"""add simple_tags column to sale

Revision ID: 7dd13301ed4b
Revises: e3f3dfe78502
Create Date: 2025-08-04 22:22:42.180389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '7dd13301ed4b'
down_revision = 'e3f3dfe78502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('simple_tags', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_column('simple_tags')

    # ### end Alembic commands ###
