"""create CarTIP table

Revision ID: f9ef7b92448b
Revises: 
Create Date: 2025-08-03 20:28:08.577121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'f9ef7b92448b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_tip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('images', sqlite.JSON(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date', sa.String(length=100), nullable=False),
    sa.Column('view', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_tip')
    # ### end Alembic commands ###
