"""recreate sale table

Revision ID: ff493257c261
Revises: 2e466053d095
Create Date: 2025-08-05 18:03:57.304770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'ff493257c261'
down_revision = '2e466053d095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('fuel', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('trim', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('mileage', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('manufacturer', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('sub_model', sa.String(length=50), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('thumbnail', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('images', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('simple_tags', sqlite.JSON(), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sale_backup')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale_backup',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('fuel', sa.VARCHAR(length=50), nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('trim', sa.VARCHAR(length=50), nullable=True),
    sa.Column('year', sa.VARCHAR(length=20), nullable=True),
    sa.Column('mileage', sa.VARCHAR(length=50), nullable=True),
    sa.Column('color', sa.VARCHAR(length=30), nullable=True),
    sa.Column('price', sa.VARCHAR(length=50), nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=50), nullable=True),
    sa.Column('model', sa.VARCHAR(length=50), nullable=True),
    sa.Column('sub_model', sa.VARCHAR(length=50), nullable=True),
    sa.Column('grade', sa.VARCHAR(length=50), nullable=True),
    sa.Column('thumbnail', sa.TEXT(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=False),
    sa.Column('images', sqlite.JSON(), nullable=True),
    sa.Column('simple_tags', sqlite.JSON(), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sale')
    # ### end Alembic commands ###
